name: Build UWP for Xbox

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      # Étape 1 - Checkout
      - name: Checkout code
        uses: actions/checkout@v4

      # Étape 2 - Installation outils
      - name: Install UWP Tools
        shell: pwsh
        run: |
          $installerPath = "$env:RUNNER_TEMP\vs_buildtools.exe"
          Invoke-WebRequest -Uri "https://aka.ms/vs/17/release/vs_buildtools.exe" -OutFile $installerPath
          Start-Process -Wait -FilePath $installerPath -ArgumentList @(
            '--quiet', '--wait', '--norestart',
            '--add Microsoft.VisualStudio.Workload.Universal',
            '--add Microsoft.VisualStudio.Component.Windows10SDK.19041'
          )

      # Étape 3 - Setup MSBuild
      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2

      # Étape 4 - Génération projet (version corrigée)
      - name: Generate Project Files
        shell: pwsh
        run: |
          # Fichier .csproj
          if (-not (Test-Path "Xbox-UWP-App.csproj")) {
              $csprojContent = @'
<Project DefaultTargets="Build" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <PropertyGroup>
    <Configuration Condition=" '$(Configuration)' == '' ">Debug</Configuration>
    <Platform Condition=" '$(Platform)' == '' ">x64</Platform>
    <ProjectGuid>{$([System.Guid]::NewGuid())}</ProjectGuid>
    <OutputType>AppContainerExe</OutputType>
    <RootNamespace>Xbox_UWP_App</RootNamespace>
    <AssemblyName>Xbox-UWP-App</AssemblyName>
    <TargetPlatformIdentifier>UAP</TargetPlatformIdentifier>
    <TargetPlatformVersion>10.0.19041.0</TargetPlatformVersion>
    <MinimumVisualStudioVersion>14</MinimumVisualStudioVersion>
  </PropertyGroup>
  <ItemGroup>
    <AppxManifest Include="Package.appxmanifest"/>
  </ItemGroup>
  <Import Project="$(MSBuildExtensionsPath)\Microsoft\WindowsXaml\v$(VisualStudioVersion)\Microsoft.Windows.UI.Xaml.CSharp.targets"/>
</Project>
'@
              $csprojContent | Out-File -FilePath "Xbox-UWP-App.csproj" -Encoding UTF8
          }

          # Fichier .sln
          if (-not (Test-Path "Xbox-UWP-App.sln")) {
              dotnet new sln --name "Xbox-UWP-App"
              dotnet sln add "Xbox-UWP-App.csproj"
          }

      # Étape 5 - Build
      - name: Build Solution
        run: |
          msbuild Xbox-UWP-App.sln `
            /p:Configuration=Release `
            /p:Platform=x64 `
            /p:AppxBundle=Always `
            /p:AppxBundlePlatforms="x64" `
            /p:UapAppxPackageBuildMode=StoreUpload

      # Étape 6 - Upload
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: AppPackage
          path: bin/x64/Release/AppPackages/
