name: Build Xbox UWP App Package

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    timeout-minutes: 20

    steps:
      # Étape 1 - Checkout du code
      - name: Checkout repository
        uses: actions/checkout@v4

      # Étape 2 - Configuration MSBuild
      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1
        with:
          vs-version: '17.0'

      # Étape 3 - Correction du fichier projet
      - name: Fix project configuration
        shell: pwsh
        run: |
          # Ajoute les propriétés manquantes au fichier csproj
          $projContent = Get-Content -Path Xbox-UWP-App.csproj -Raw
          $newContent = $projContent -replace '<PropertyGroup>', '<PropertyGroup>
            <OutputPath>bin\$(Configuration)\$(Platform)</OutputPath>
            <IntermediateOutputPath>obj\$(Configuration)\$(Platform)</IntermediateOutputPath>
            <AppxPackageDir>$(MSBuildThisFileDirectory)AppPackages\</AppxPackageDir>
            <RestoreProjectStyle>PackageReference</RestoreProjectStyle>
            <NuGetTargetMoniker>UAP,Version=v10.0.19041</NuGetTargetMoniker>'
          $newContent | Set-Content -Path Xbox-UWP-App.csproj

      # Étape 4 - Build avec MSBuild
      - name: Build AppX package
        shell: pwsh
        run: |
          msbuild Xbox-UWP-App.csproj `
            /t:Restore;Build;Publish `
            /p:Configuration=Release `
            /p:Platform=x64 `
            /p:AppxBundle=Never `
            /p:UapAppxPackageBuildMode=StoreUpload `
            /p:AppxPackageDir="$(Build.SourcesDirectory)\AppPackages\" `
            /p:AppxPackageOutputDir="$(Build.SourcesDirectory)\AppPackages\" `
            /p:GenerateAppxPackageOnBuild=true `
            /p:WindowsTargetPlatformVersion=10.0.19041.0 `
            /p:VisualStudioVersion=17.0 `
            /p:RestoreForce=true

      # Étape 5 - Vérification des fichiers générés
      - name: List generated files
        shell: pwsh
        run: |
          Get-ChildItem -Path . -Recurse -Filter *.appx | ForEach-Object { Write-Output $_.FullName }
          Get-ChildItem -Path . -Recurse -Filter *.appxsym | ForEach-Object { Write-Output $_.FullName }

      # Étape 6 - Publication des artefacts
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: xbox-app-package
          path: |
            ./**/*.appx
            ./**/*.appxsym
          retention-days: 5
