name: Build Xbox UWP Package

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    timeout-minutes: 20

    steps:
      # Étape 1 - Checkout du code
      - name: Checkout repository
        uses: actions/checkout@v4

      # Étape 2 - Configuration MSBuild
      - name: Setup build tools
        uses: microsoft/setup-msbuild@v1
        with:
          vs-version: '17.0'

      # Étape 3 - Patch du fichier projet (critical fix)
      - name: Fix project configuration
        shell: pwsh
        run: |
          Add-Content -Path Xbox-UWP-App.csproj -Value @'
<PropertyGroup>
  <OutputPath>bin\$(Configuration)\$(Platform)</OutputPath>
  <IntermediateOutputPath>obj\$(Configuration)\$(Platform)</IntermediateOutputPath>
  <AppxPackageDir>$(MSBuildThisFileDirectory)AppPackages\</AppxPackageDir>
  <RestoreProjectStyle>PackageReference</RestoreProjectStyle>
</PropertyGroup>
'@

      # Étape 4 - Restauration et build en une passe
      - name: Build AppX package
        run: |
          msbuild Xbox-UWP-App.sln `
            /t:Restore `
            /p:Configuration=Release `
            /p:Platform=x64 `
            /p:AppxBundle=Never `
            /p:UapAppxPackageBuildMode=StoreUpload `
            /p:WindowsTargetPlatformVersion=10.0.19041.0 `
            /p:VisualStudioVersion=17.0 `
            /p:RestoreForce=true `
            /p:RestorePackagesConfig=true

      # Étape 5 - Publication des artefacts
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: xbox-app-package
          path: |
            ./AppPackages/**/*.appx
            ./AppPackages/**/*.appxsym
          retention-days: 5
