name: Build Xbox UWP App Package

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    timeout-minutes: 20

    steps:
      # Étape 1 - Checkout du code
      - name: Checkout repository
        uses: actions/checkout@v4

      # Étape 2 - Configuration MSBuild
      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1
        with:
          vs-version: '17.0'

      # Étape 3 - Correction du fichier projet
      - name: Fix project configuration
        shell: pwsh
        run: |
          # Créer le dossier AppPackages s'il n'existe pas
          New-Item -ItemType Directory -Path "./AppPackages" -Force
          
          # Modifier le fichier csproj si nécessaire
          $projContent = Get-Content -Path Xbox-UWP-App.csproj -Raw
          $newContent = $projContent -replace '<PropertyGroup>', '<PropertyGroup>
            <AppxPackageDir>$(MSBuildThisFileDirectory)AppPackages\</AppxPackageDir>
            <OutputPath>bin\$(Configuration)\$(Platform)</OutputPath>
            <IntermediateOutputPath>obj\$(Configuration)\$(Platform)</IntermediateOutputPath>'
          $newContent | Set-Content -Path Xbox-UWP-App.csproj

      # Étape 4 - Build avec MSBuild
      - name: Build AppX package
        run: |
          msbuild Xbox-UWP-App.sln `
            /p:Configuration=Release `
            /p:Platform=x64 `
            /p:AppxBundle=Never `
            /p:UapAppxPackageBuildMode=StoreUpload `
            /p:WindowsTargetPlatformVersion=10.0.19041.0 `
            /p:VisualStudioVersion=17.0 `
            /p:AppxPackageDir="$($pwd.Path)\AppPackages\"

      # Étape 5 - Vérification des artefacts
      - name: Verify artifacts
        shell: pwsh
        run: |
          $artifacts = Get-ChildItem -Path . -Recurse -Include *.appx, *.appxsym
          if (-not $artifacts) {
              Write-Output "##[error] Aucun fichier .appx ou .appxsym trouvé"
              exit 1
          }
          Write-Output "Fichiers trouvés:"
          $artifacts | ForEach-Object { Write-Output $_.FullName }

      # Étape 6 - Publication des artefacts
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: xbox-app-package
          path: |
            ./AppPackages/**/*.appx
            ./AppPackages/**/*.appxsym
          if-no-files-found: error
          retention-days: 5
