name: Build Xbox UWP App Package

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    timeout-minutes: 30

    steps:
      # Étape 1 - Checkout du code
      - name: Checkout repository
        uses: actions/checkout@v4

      # Étape 2 - Installation des composants requis
      - name: Install UWP dependencies
        run: choco install windows-sdk-10.0.19041 --version=10.0.19041.0 -y

      # Étape 3 - Configuration MSBuild
      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1
        with:
          vs-version: '17.0'
          uwp: true

      # Étape 4 - Build avec MSBuild
      - name: Build AppX package
        shell: cmd
        run: |
          msbuild Xbox-UWP-App.csproj ^
            /p:Configuration=Release ^
            /p:Platform=x64 ^
            /p:AppxBundle=Never ^
            /p:UapAppxPackageBuildMode=StoreUpload ^
            /p:WindowsTargetPlatformVersion=10.0.19041.0 ^
            /p:RestoreForce=true ^
            /p:GenerateAppxPackageOnBuild=true ^
            /p:AppxPackageDir="AppPackages" ^
            /p:AppxPackageOutputDir="AppPackages"

      # Étape 5 - Vérification des fichiers
      - name: Verify AppX package
        shell: pwsh
        run: |
          $appxFiles = Get-ChildItem -Path . -Recurse -Filter *.appx
          if (!$appxFiles) {
              Write-Error "No .appx files found!"
              Get-ChildItem -Path . -Recurse | Out-Host
              exit 1
          }
          $appxFiles | ForEach-Object { Write-Output "Found: $($_.FullName)" }

      # Étape 6 - Publication des artefacts
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: xbox-app-package
          path: |
            ./**/*.appx
            ./**/*.appxsym
          if-no-files-found: error
          retention-days: 5
