name: Build Xbox UWP App Package

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    timeout-minutes: 20

    steps:
      # Étape 1 - Checkout du code
      - name: Checkout repository
        uses: actions/checkout@v4

      # Étape 2 - Configuration MSBuild
      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1
        with:
          vs-version: '17.0'

      # Étape 3 - Correction du fichier projet
      - name: Fix project configuration
        shell: pwsh
        run: |
          # Ajoute les propriétés manquantes au fichier csproj
          $projContent = Get-Content -Path Xbox-UWP-App.csproj -Raw
          $newContent = $projContent -replace '<PropertyGroup>', '<PropertyGroup>
            <OutputPath>bin\$(Configuration)\$(Platform)</OutputPath>
            <IntermediateOutputPath>obj\$(Configuration)\$(Platform)</IntermediateOutputPath>
            <AppxPackageDir>$(MSBuildThisFileDirectory)AppPackages\</AppxPackageDir>
            <RestoreProjectStyle>PackageReference</RestoreProjectStyle>
            <NuGetTargetMoniker>UAP,Version=v10.0.19041</NuGetTargetMoniker>'
          $newContent | Set-Content -Path Xbox-UWP-App.csproj
      # Étape 4 - Build avec MSBuild
      - name: Build AppX package
        run: |
          msbuild Xbox-UWP-App.sln `
            /t:Restore `
            /p:Configuration=Release `
            /p:Platform=x64 `
            /p:AppxBundle=Never `
            /p:UapAppxPackageBuildMode=StoreUpload `
            /p:WindowsTargetPlatformVersion=10.0.19041.0 `
            /p:VisualStudioVersion=17.0 `
            /p:RestoreForce=true `
            /p:RestorePackagesConfig=true
      # Étape 5 - Publication des artefacts
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: xbox-app-package
          path: |
            ./AppPackages/**/*.appx
            ./AppPackages/**/*.appxsym
          retention-days: 5

      # Optionnel: Déploiement sur Xbox Dev Kit
      - name: Deploy to Xbox (Optional)
        if: false  # Mettre à true pour activer
        shell: pwsh
        run: |
          $xboxIp = "192.168.1.X"  # Remplacer par l'IP de votre Xbox
          $xboxPin = "123456"       # Remplacer par votre PIN
          $appxFile = Get-ChildItem -Path ./AppPackages -Filter *.appx -Recurse | Select-Object -First 1
          
          if ($appxFile) {
              Write-Output "Deploying $($appxFile.FullName) to Xbox..."
              Start-Process "WinAppDeployCmd.exe" -ArgumentList @(
                  "install",
                  "-file", "`"$($appxFile.FullName)`"",
                  "-ip", $xboxIp,
                  "-pin", $xboxPin
              ) -Wait -NoNewWindow
          } else {
              Write-Error "No .appx file found in AppPackages folder"
              exit 1
          }
