name: Build Xbox UWP App Package

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    timeout-minutes: 20

    steps:
      # Étape 1 - Checkout du code
      - name: Checkout repository
        uses: actions/checkout@v4

      # Étape 2 - Configuration MSBuild
      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1
        with:
          vs-version: '17.0'

      # Étape 3 - Préparation des répertoires
      - name: Prepare directories
        shell: pwsh
        run: |
          # Créer le répertoire AppPackages explicitement
          New-Item -ItemType Directory -Path "./AppPackages" -Force
          Write-Output "Répertoire AppPackages créé à: $($pwd.Path)\AppPackages"

      # Étape 4 - Build avec MSBuild (version modifiée)
      - name: Build AppX package
        shell: pwsh
        run: |
          # Commande MSBuild avec sortie détaillée
          msbuild Xbox-UWP-App.sln `
            /p:Configuration=Release `
            /p:Platform=x64 `
            /p:AppxBundle=Never `
            /p:UapAppxPackageBuildMode=StoreUpload `
            /p:WindowsTargetPlatformVersion=10.0.19041.0 `
            /p:AppxPackageDir="$($pwd.Path)\AppPackages\" `
            /p:AppxPackageOutputDir="$($pwd.Path)\AppPackages\" `
            /p:GenerateAppxPackageOnBuild=true `
            /p:BuildAppxUploadPackageForUap=true `
            /verbosity:diagnostic

          # Diagnostic: Lister tous les fichiers .appx générés
          Write-Output "=== Recherche des fichiers .appx ==="
          Get-ChildItem -Path . -Recurse -Filter *.appx | ForEach-Object {
              Write-Output "Trouvé: $($_.FullName)"
          }

      # Étape 5 - Vérification des artefacts
      - name: Verify artifacts
        shell: pwsh
        run: |
          $appxFiles = Get-ChildItem -Path ./AppPackages -Filter *.appx -Recurse
          if (-not $appxFiles) {
              Write-Output "##[error] Aucun fichier .appx trouvé dans AppPackages"
              Write-Output "Contenu de AppPackages:"
              Get-ChildItem -Path ./AppPackages -Recurse
              exit 1
          }
          Write-Output "Fichiers .appx trouvés:"
          $appxFiles | ForEach-Object { Write-Output $_.FullName }

      # Étape 6 - Publication des artefacts
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: xbox-app-package
          path: ./AppPackages/
          if-no-files-found: error
          retention-days: 5
