name: Build Xbox UWP App Package

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    timeout-minutes: 20

    steps:
      # Étape 1 - Checkout du code
      - name: Checkout repository
        uses: actions/checkout@v4

      # Étape 2 - Configuration MSBuild
      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1
        with:
          vs-version: '17.0'

      # Étape 3 - Définir la version du projet
      - name: Set project version
        shell: pwsh
        run: |
          # Ajouter une version explicite au fichier csproj
          $projContent = Get-Content -Path Xbox-UWP-App.csproj -Raw
          if (-not $projContent.Contains('<Version>')) {
              $newContent = $projContent -replace '<PropertyGroup>', '<PropertyGroup>
                <Version>1.0.0</Version>'
              $newContent | Set-Content -Path Xbox-UWP-App.csproj
          }

          # Créer le dossier AppPackages
          New-Item -ItemType Directory -Path "./AppPackages" -Force

      # Étape 4 - Build avec MSBuild
      - name: Build AppX package
        run: |
          msbuild Xbox-UWP-App.sln `
            /p:Configuration=Release `
            /p:Platform=x64 `
            /p:AppxBundle=Never `
            /p:UapAppxPackageBuildMode=StoreUpload `
            /p:WindowsTargetPlatformVersion=10.0.19041.0 `
            /p:VisualStudioVersion=17.0 `
            /p:AppxPackageDir="$($pwd.Path)\AppPackages\" `
            /p:RestorePackages=false `
            /p:DisableNuGetToolset=true

      # Étape 5 - Publication des artefacts
      - name: Upload artifacts
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: xbox-app-package
          path: ./AppPackages/
          if-no-files-found: error
          retention-days: 5
