name: Build Xbox UWP App Package

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    timeout-minutes: 20

    steps:
      # Étape 1 - Checkout
      - uses: actions/checkout@v4

      # Étape 2 - Setup MSBuild
      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1
        with:
          vs-version: '17.0'

      # Étape 3 - Nettoyage et création des dossiers
      - name: Prepare directories
        shell: pwsh
        run: |
          Remove-Item -Path AppPackages -Recurse -Force -ErrorAction SilentlyContinue
          New-Item -ItemType Directory -Path AppPackages -Force
          Write-Host "Dossier AppPackages créé à : $(Resolve-Path ./AppPackages)"

      # Étape 4 - Build avec chemins absolus
      - name: Build AppX package
        shell: pwsh
        run: |
          $solutionPath = Resolve-Path -Path "Xbox-UWP-App.sln"
          $appxPackageDir = "$env:GITHUB_WORKSPACE\AppPackages"
          
          msbuild $solutionPath `
            /t:Restore `
            /p:Configuration=Release `
            /p:Platform=x64 `
            /p:AppxBundle=Never `
            /p:UapAppxPackageBuildMode=StoreUpload `
            /p:AppxPackageDir="$appxPackageDir" `
            /p:OutputPath="$env:GITHUB_WORKSPACE\bin\Release\x64" `
            /p:WindowsTargetPlatformVersion=10.0.19041.0 `
            /clp:ErrorsOnly

      # Étape 5 - Vérification améliorée
      - name: Verify output
        shell: pwsh
        run: |
          $appxFiles = Get-ChildItem -Path "$env:GITHUB_WORKSPACE\AppPackages" -Recurse -Include *.appx, *.appxbundle
          
          if ($appxFiles.Count -eq 0) {
              Write-Host "::error::AUCUN FICHIER TROUVÉ. Contenu de AppPackages :"
              Get-ChildItem -Path "$env:GITHUB_WORKSPACE\AppPackages" -Recurse | Format-Table FullName
              exit 1
          }
          
          Write-Host "Fichiers générés :"
          $appxFiles | ForEach-Object { Write-Host "- $($_.FullName)" }

      # Étape 6 - Upload
      - uses: actions/upload-artifact@v4
        with:
          name: xbox-package
          path: ${{ github.workspace }}/AppPackages/
          retention-days: 5
