name: Build Xbox UWP App Package

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    timeout-minutes: 20

    steps:
      # Étape 1 - Checkout
      - uses: actions/checkout@v4

      # Étape 2 - Setup MSBuild
      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1
        with:
          vs-version: '17.0'

      # Étape 3 - Création du dossier (obligatoire)
      - name: Create AppPackages directory
        shell: cmd
        run: mkdir AppPackages

      # Étape 4 - Patch du .csproj (sans commentaires problématiques)
      - name: Fix project configuration
        shell: pwsh
        run: |
          $projContent = Get-Content -Path Xbox-UWP-App.csproj -Raw
          $newContent = $projContent -replace '<PropertyGroup>', '<PropertyGroup>
            <OutputPath>bin\$(Configuration)\$(Platform)</OutputPath>
            <IntermediateOutputPath>obj\$(Configuration)\$(Platform)</IntermediateOutputPath>
            <AppxPackageDir>$(MSBuildThisFileDirectory)AppPackages\</AppxPackageDir>
            <RestoreProjectStyle>PackageReference</RestoreProjectStyle>
            <NuGetTargetMoniker>UAP,Version=v10.0.19041</NuGetTargetMoniker>'
          $newContent | Set-Content -Path Xbox-UWP-App.csproj

      # Étape 5 - Build (syntaxe batch sécurisée)
      - name: Build AppX package
        shell: cmd
        run: |
          msbuild Xbox-UWP-App.sln ^
            /t:Restore ^
            /p:Configuration=Release ^
            /p:Platform=x64 ^
            /p:AppxBundle=Never ^
            /p:UapAppxPackageBuildMode=StoreUpload ^
            /p:WindowsTargetPlatformVersion=10.0.19041.0 ^
            /p:VisualStudioVersion=17.0 ^
            /p:RestoreForce=true ^
            /p:RestorePackagesConfig=true

      # Étape 6 - Vérification des fichiers
      - name: Verify AppX output
        shell: pwsh
        run: |
          $files = Get-ChildItem -Path AppPackages -Recurse -Include *.appx, *.appxsym
          if (-not $files) {
              Write-Error "ERREUR : Aucun fichier .appx généré"
              exit 1
          }
          Write-Host "Fichiers produits :"
          $files | ForEach-Object { Write-Host "- $($_.Name)" }

      # Étape 7 - Upload
      - uses: actions/upload-artifact@v4
        with:
          name: xbox-app-package
          path: AppPackages/
          retention-days: 5

      # Déploiement Xbox (optionnel - désactivé par défaut)
      - name: Deploy to Xbox
        if: false
        shell: cmd
        run: |
          WinAppDeployCmd install ^
            -file "AppPackages\*.appx" ^
            -ip 192.168.1.X ^  # Remplacez par l'IP réelle
            -pin 123456         # Remplacez par votre PIN
