name: Build UWP for Xbox

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      # Étape 1 - Checkout du code
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Étape 2 - Installation des outils UWP
      - name: Install UWP Tools
        shell: pwsh
        run: |
          # Téléchargement du VS Build Tools
          $installerPath = "$env:RUNNER_TEMP\vs_buildtools.exe"
          Invoke-WebRequest -Uri "https://aka.ms/vs/17/release/vs_buildtools.exe" -OutFile $installerPath
          
          # Installation des composants requis
          Start-Process -Wait -FilePath $installerPath -ArgumentList @(
            '--quiet',
            '--wait',
            '--norestart',
            '--add Microsoft.VisualStudio.Workload.Universal',
            '--add Microsoft.VisualStudio.Component.Windows10SDK.19041'
          )

      # Étape 3 - Configuration MSBuild
      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2

      # Étape 4 - Vérification du projet
      - name: Validate Project Structure
        shell: pwsh
        run: |
          $requiredFiles = @(
              "Xbox-UWP-App.sln",
              "Xbox-UWP-App/Xbox-UWP-App.csproj",
              "Xbox-UWP-App/Package.appxmanifest"
          )
          
          foreach ($file in $requiredFiles) {
              if (-not (Test-Path $file)) {
                  Write-Error "File missing: $file"
                  Get-ChildItem -Recurse
                  exit 1
              }
          }

      # Étape 5 - Restauration NuGet
      - name: Restore Packages
        run: nuget restore Xbox-UWP-App.sln

      # Étape 6 - Compilation
      - name: Build Solution
        shell: pwsh
        run: |
          $msbuildArgs = @(
              "Xbox-UWP-App.sln",
              "/p:Configuration=Release",
              "/p:Platform=x64",
              "/p:AppxBundle=Always",
              "/p:AppxBundlePlatforms=`"x64`"",
              "/p:UapAppxPackageBuildMode=StoreUpload",
              "/m",
              "/nr:false",
              "/detailedsummary",
              "/flp:`"v=diag;logfile=build.log`""
          )
          
          msbuild @msbuildArgs
          if ($LASTEXITCODE -ne 0) { exit $LASTEXITCODE }

      # Étape 7 - Publication des artefacts
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: AppPackage
          path: |
            Xbox-UWP-App/bin/x64/Release/AppPackages/
            build.log
          if-no-files-found: error
          retention-days: 3
