name: Build UWP for Xbox

on: [push]

jobs:
  build:
    runs-on: windows-latest

    steps:
      # Étape 1: Récupération du code
      - name: Checkout code
        uses: actions/checkout@v4

      # Étape 2: Configuration de MSBuild
      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1.3
        with:
          vs-version: '17.0'  # Visual Studio 2022

      # Étape 3: Installation des dépendances UWP
      - name: Install UWP dependencies
        run: |
          choco install visualstudio2022-workload-universalbuildtools -y --no-progress
          refreshenv

      # Étape 4: Compilation
      - name: Build Solution
        run: |
          msbuild Xbox-UWP-App.sln /p:Configuration=Release /p:Platform=x64 /p:AppxBundle=Always /p:AppxBundlePlatforms="x64" /p:UapAppxPackageBuildMode=StoreUpload

      # Étape 5: Upload du package
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: AppPackage
          path: bin/x64/Release/AppPackages/
          retention-days: 1
