name: Build UWP for Xbox

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      # Étape 1 - Checkout du code
      - name: Checkout repository
        uses: actions/checkout@v4

      # Étape 2 - Installation garantie des outils UWP
      - name: Install UWP Workload
        shell: pwsh
        run: |
          # Téléchargement du VS Installer minimal
          $installerPath = "$env:RUNNER_TEMP\vs_buildtools.exe"
          Invoke-WebRequest -Uri "https://aka.ms/vs/17/release/vs_buildtools.exe" -OutFile $installerPath
          
          # Installation silencieuse des composants requis
          Start-Process -FilePath $installerPath -ArgumentList @(
            '--quiet',
            '--wait',
            '--norestart',
            '--add Microsoft.VisualStudio.Workload.Universal',
            '--add Microsoft.VisualStudio.Component.Windows10SDK.19041'
          ) -Wait -NoNewWindow

          # Ajout au PATH
          $msbuildPath = "${env:ProgramFiles(x86)}\Microsoft Visual Studio\2022\BuildTools\MSBuild\Current\Bin"
          echo "$msbuildPath" | Out-File -FilePath $env:GITHUB_PATH -Append

      # Étape 3 - Configuration MSBuild
      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2

      # Étape 4 - Vérification de l'environnement
      - name: Verify Installation
        shell: pwsh
        run: |
          $msbuildPath = "${env:ProgramFiles(x86)}\Microsoft Visual Studio\2022\BuildTools\MSBuild\Current\Bin\MSBuild.exe"
          if (-not (Test-Path $msbuildPath)) {
              Write-Host "##[error]MSBuild not found at $msbuildPath"
              Get-ChildItem "${env:ProgramFiles(x86)}\Microsoft Visual Studio\2022\" -Recurse -Filter "MSBuild.exe" | Select-Object FullName
              exit 1
          }
          & $msbuildPath /version

      # Étape 5 - Restauration NuGet
      - name: Restore Packages
        run: nuget restore Xbox-UWP-App.sln

      # Étape 6 - Compilation
      - name: Build Solution
        shell: pwsh
        run: |
          $msbuildPath = "${env:ProgramFiles(x86)}\Microsoft Visual Studio\2022\BuildTools\MSBuild\Current\Bin\MSBuild.exe"
          & $msbuildPath Xbox-UWP-App.sln `
            /p:Configuration=Release `
            /p:Platform=x64 `
            /p:AppxBundle=Always `
            /p:AppxBundlePlatforms="x64" `
            /p:UapAppxPackageBuildMode=StoreUpload `
            /detailedsummary `
            /flp1:v=diag;logfile=build_diagnostics.log

      # Étape 7 - Publication des artefacts
      - name: Upload Package
        uses: actions/upload-artifact@v4
        with:
          name: AppPackage
          path: bin/x64/Release/AppPackages/
          if-no-files-found: error
          retention-days: 3

      # Étape 8 - Backup des logs
      - name: Upload Logs
        uses: actions/upload-artifact@v4
        with:
          name: BuildLogs
          path: |
            build_diagnostics.log
            **/*.binlog
          retention-days: 7
