name: Build UWP for Xbox

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      # Étape 1 - Checkout du code
      - name: Checkout repository
        uses: actions/checkout@v4

      # Étape 2 - Configuration MSBuild
      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2

      # Étape 3 - Installation des composants UWP
      - name: Install UWP Build Tools
        run: |
          # Installation via le VS Installer
          $installPath = & "${env:ProgramFiles(x86)}\Microsoft Visual Studio\Installer\vswhere.exe" -latest -property installationPath
          & "$installPath\Common7\IDE\VSInstaller.exe" modify `
            --installPath "$installPath" `
            --add Microsoft.VisualStudio.Workload.Universal `
            --add Microsoft.VisualStudio.ComponentGroup.UWP.BuildTools `
            --quiet --norestart --wait

      # Étape 4 - Vérification de l'environnement
      - name: Verify Environment
        run: |
          msbuild /version
          nuget help

      # Étape 5 - Restauration des packages NuGet
      - name: Restore NuGet Packages
        run: nuget restore Xbox-UWP-App.sln

      # Étape 6 - Compilation avec logging détaillé
      - name: Build Solution
        run: |
          msbuild Xbox-UWP-App.sln `
            /p:Configuration=Release `
            /p:Platform=x64 `
            /p:AppxBundle=Always `
            /p:AppxBundlePlatforms="x64" `
            /p:UapAppxPackageBuildMode=StoreUpload `
            /detailedsummary `
            /flp1:v=diag;logfile=build_diagnostics.log `
            /flp2:errorsonly;logfile=build_errors.log `
            /flp3:warningsonly;logfile=build_warnings.log

      # Étape 7 - Upload des artefacts
      - name: Upload App Package
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: AppPackage
          path: bin/x64/Release/AppPackages/
          retention-days: 3

      # Étape 8 - Upload des logs en cas d'échec
      - name: Upload Build Logs
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: BuildLogs
          path: |
            build_diagnostics.log
            build_errors.log
            build_warnings.log
          retention-days: 7
